spring: 
  profiles: 
    active: 
      - dev
---
server:
  port: 7002

spring: 
  profiles: dev
  aoolication: microcloud-config-eureka-client
  
eureka: 
  instance:
    hostname: eureka7002.com  #eureka服务端的实例名
  client: 
    register-with-eureka: false #false表示不向eureka注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://eureka7002.com:7002/eureka/
   
  server:
    peer-node-read-timeout-ms: 60000    #那个节点出现 Read timed out。只需要加上这句话即可解决

---
server:
  port: 7001

spring: 
  profiles: test
  aoolication: microcloud-config-eureka-client

eureka: 
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名
  client: 
    register-with-eureka: false #false表示不向eureka注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
   
  server:
    peer-node-read-timeout-ms: 60000    #那个节点出现 Read timed out。只需要加上这句话即可解决