spring: 
  profiles: 
    active: 
      - dev
---
server: 
  port: 8201
spring: 
  profiles: dev
  application: 
    name: microcloud-config-config-client
eureka: 
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
info:
  app.name: BUS-microcloud
  company.name: www.hdu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8202
spring: 
  profiles: test	#test
  application: 
    name: microcloud-config-config-client
eureka: 
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/